/* Standalone planning prototype. Hashes select concepts; displayed paths specify proposed product routes. */
const scenes = {
 result:['Employee · Analysis success','Análise salva · PR #7','/workspace/people/2/analyses/92?view=summary','employee','analyses'],
 managerframework:['Manager · Official framework','Framework oficial','/manage/career/framework?level=L4','manager','roles'],
 managereadonly:['Manager · Read evidence','Evidência capturada','/workspace/people/3/evidence/42','manager','people'],
 criterion:['Employee · Criterion detail','Security','/app/framework/criteria/criterion-security-l4?level=L4','employee','framework'],
 overview:['Employee · Overview','Visão geral','/app/overview','employee','overview'],
 inbox:['Employee · Bounded inbox','Caixa de entrada','/app/inbox?status=pending','employee','inbox'],
 evidence:['Employee · Focused evidence','Trusted analysis · PR #7','/workspace/people/2/evidence/41','employee','inbox'],
 analyses:['Employee · Saved analyses','Análises','/app/analyses','employee','analyses'],
 analysis:['Shared · Analysis summary','Comunicação · #platform','/workspace/people/3/analyses/91?view=summary','employee','analyses'],
 history:['Shared · Review history','Comunicação · #platform','/workspace/people/3/analyses/91?view=history','employee','analyses'],
 source:['Shared · Immutable source','Comunicação · #platform','/workspace/people/3/analyses/91?view=source','employee','analyses'],
 reports:['Employee · Reports','Relatórios de análises','/app/analyses/reports?view=sources','employee','analyses'],
 framework:['Employee · Framework + gaps','Framework','/app/framework?level=L4&support=all','employee','framework'],
 plan:['Employee · Career plan','Plano de carreira','/app/career-plan?view=objectives','employee','plan'],
 context:['Employee · Career context','Plano de carreira','/app/career-plan?view=context','employee','plan'],
 integrations:['Employee · GitHub connection','GitHub','/app/integrations/github?view=connection','employee','integrations'],
 sync:['Employee · GitHub sync','Sincronização do GitHub','/app/integrations/github?view=sync','employee','integrations'],
 import:['Employee · Import a PR','Importar pull request','/app/integrations/github/import','employee','integrations'],
 people:['Manager · People workspace','Pessoas','/manage/people/3/career-plan?view=objectives','manager','people'],
 managerplan:['Manager · Edit career context','Contexto de carreira','/manage/people/3/career-plan?view=context','manager','people'],
 managerevidence:['Manager · Person evidence','Evidências de Maria','/manage/people/3/evidence','manager','people'],
 manageranalyses:['Manager · Person analyses','Análises de Maria','/manage/people/3/analyses','manager','people'],
 reviews:['Manager · Review queue','Revisões','/manage/reviews?status=unreviewed','manager','reviews'],
 review:['Manager · Review decision','Revisar análise','/workspace/people/3/analyses/91?view=review','manager','reviews'],
 roles:['Manager · Career configuration','Configuração de carreira','/manage/career/roles','manager','roles'],
 role:['Manager · Role detail','Engenharia de Software','/manage/career/roles/1','manager','roles'],
 terminology:['Manager · Terminology','Terminologia da organização','/manage/career/terminology','manager','roles'],
 loading:['States · Loading','Caixa de entrada','/app/inbox?status=pending','employee','inbox'],
 empty:['States · Empty inbox','Caixa de entrada','/app/inbox?status=pending','employee','inbox'],
 error:['States · Recoverable error','Caixa de entrada','/app/inbox?status=pending','employee','inbox'],
 denied:['States · Permission denied','Permissão necessária','/manage/people','employee','overview'],
 mobile:['Mobile · Drawer + inbox','Caixa de entrada','/app/inbox?status=pending','employee','inbox'],
 landing:['Public · Scrolling landing','Promova','/','public',''],
 login:['Auth · Focused login','Entrar','/login','public',''],
 register:['Auth · Focused registration','Criar conta','/register','public','']
};
let current='overview';
let reviewerDraft='';
let observationDraft='';
const root=document.getElementById('surface');
const selector=document.getElementById('scenario');
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const link=(key,label,cls='')=>`<a class="${cls}" href="#${key}">${label}</a>`;
const action=(label,kind='notice',cls='',message='Interação ilustrativa; nenhum dado foi enviado.')=>`<button class="${cls}" data-${kind}="${esc(message)}">${label}</button>`;
const badge=(label,type='')=>`<span class="badge ${type}">${label}</span>`;
const tabs=(items,active)=>`<nav class="tabs" aria-label="Seções da visualização">${items.map(([key,label])=>`<a href="#${key}" ${key===active?'aria-current="page"':''}>${label}</a>`).join('')}</nav>`;
const panel=(title,body,foot='',cls='')=>`<section class="panel ${cls}"><div class="panel-head"><h2>${title}</h2></div><div class="panel-body">${body}</div>${foot?`<div class="panel-foot">${foot}</div>`:''}</section>`;
const pager=(count=25)=>`<span>${count<=25?`1–${count} de ${count}`:'1–25 de '+count}</span><div class="actions"><button disabled>Anterior</button><button ${count<=25?'disabled':''} data-notice="Paginação proposta: carregar próxima página no servidor.">Próxima</button></div>`;
const field=(label,value='',type='text',extra='')=>`<label class="field">${label}<input type="${type}" value="${esc(value)}" ${extra}></label>`;
const selectField=(label,values)=>`<label class="field">${label}<select>${values.map(s=>`<option>${s}</option>`).join('')}</select></label>`;
const navEmployee=[['overview','◈','Visão geral'],['inbox','▤','Caixa de entrada'],['analyses','▥','Análises'],['framework','▦','Framework'],['plan','↗','Plano de carreira'],['integrations','⌘','Integrações']];
const navManager=[['people','◉','Pessoas'],['reviews','▤','Revisões'],['roles','▦','Configuração de carreira']];
function nav(role,selected){return `<div class="workspace-label">${role==='manager'?'Gestão':'Minha carreira'}</div><nav class="nav-links" aria-label="Principal">${(role==='manager'?navManager:navEmployee).map(([id,icon,label])=>`<a href="#${id}" ${id===selected?'aria-current="page"':''}><span class="nav-dot" aria-hidden="true">${icon}</span><span>${label}</span>${id==='inbox'&&!['loading','empty','error','denied'].includes(current)?'<span class="nav-count">4</span>':''}</a>`).join('')}</nav>`}
function brand(role='employee'){return `<a class="brand" href="#${role==='manager'?'people':role==='public'?'landing':'overview'}"><img src="../../frontend/assets/promova-symbol.png" alt="">promova</a>`}
const dateTools=()=>`<label>Período <select aria-label="Período"><option>Todo o período</option><option>Últimos 30 dias</option><option>Personalizado</option></select></label>`;
const analysisTabs=()=>tabs([['analysis','Resumo'],['source','Fonte'],['history','Histórico']],current);
const configTabs=()=>tabs([['roles','Cargos'],['terminology','Terminologia'],['managerframework','Framework']],current);
function listRow(title,meta,target='analysis',status='Não revisada',selected=false){return `<a href="#${target}" class="row ${selected?'selected':''}"><div><strong>${title}</strong><small>${meta}</small></div>${status?`<span class="trailing">${badge(status,status==='Pendente'?'purple':'')}</span>`:''}<span aria-hidden="true">›</span></a>`}
function sourceCopy(){return `<div class="source"><p><strong>PR #7 · PromovaGD/Promova</strong><br>Autor: joaorihan · Merge em 10 ago. 2026<br>Origem: GitHub · Evidência capturada</p><p><strong>Trusted server-owned analysis</strong><br>Make analysis and persistence one authenticated, server-owned transaction. Enforce owner, profile and framework validation, immutable evidence snapshots, idempotent retries and rollback on engine failure.</p><p>Remove public/client-authored analysis writes and route the frontend through the captured-evidence workflow.</p><p><strong>Verification</strong><br>Focused ownership, transaction, engine and persistence checks. The source remains unchanged when an observation is added.</p><p>Conteúdo ilustrativo abreviado a partir do cenário capturado. A implementação deve preservar o texto integral, inclusive descrições muito longas.</p><p><a href="https://github.com/PromovaGD/Promova/pull/7" target="_blank" rel="noopener noreferrer">Abrir PR #7 no GitHub ↗</a></p></div>`}
function analysisSummary(){return `<div class="summary"><div><small>Impacto estimado</small><div class="level">L4</div></div><div><strong>Confiança média</strong><p class="sub">Contexto no momento da análise: L4 → L5</p></div></div><div class="reading"><h3>Justificativa</h3><p>Evidência forte de comunicação e liderança situacional, ainda abaixo do alvo L5 por falta de escopo estratégico amplo.</p><h3>Competências identificadas</h3><div class="tags"><span>Communication</span><span>Leadership</span><span>Incident Response</span></div><h3>Sugestões para fortalecer a evidência</h3><ul><li>Amplie o impacto para iniciativas preventivas.</li><li>Formalize um postmortem com métricas.</li></ul><p class="note">A análise organiza sinais de impacto. Ela não decide uma promoção. O plano atual pode ter mudado desde esta análise.</p></div>`}
function objectiveBody(readonly=true){return `<div class="statusline">${badge('L3 → L4','purple')}<span class="sub">Engenharia de Software</span>${readonly?badge('Somente leitura'):''}</div><a class="row" href="#${readonly?'context':'managerplan'}"><div><strong>Liderar uma entrega de ponta a ponta</strong><small>Ativo · Data alvo: 1 dez. 2026</small><p class="sub">Exemplo de objetivo para demonstrar o layout.</p></div>${badge('Ativo','green')}</a><div class="note">${readonly?'O gestor responsável mantém seu plano de carreira.':'Edite um objetivo por vez. Contexto de carreira tem um formulário separado.'}</div>`}
function personHeader(){return `<div class="person-head"><span class="avatar">MS</span><div><strong>Maria Santos</strong><p class="sub">maria.santos@empresa.com</p></div><div class="tags"><span>Engenharia</span><span>L3 → L4</span></div></div>`}
function directory(){return `<section class="panel directory"><div class="panel-head"><h2>Pessoas</h2></div><div style="padding:14px;border-bottom:1px solid var(--line)"><label class="field" style="margin:0">Nome ou e-mail<input placeholder="Buscar pessoa" id="people-search"></label></div><div class="row-list" id="people-list"><button class="row" data-notice="Este conceito detalha Maria. João usa a mesma estrutura de workspace."><div><strong>João Silva</strong><small>Engenharia · L3 → L4</small></div></button>${listRow('Maria Santos','Engenharia · L3 → L4','people','',true)}<button class="row" data-notice="Este conceito detalha Maria. Pedro usa a mesma estrutura de workspace."><div><strong>Pedro Costa</strong><small>Engenharia · L4 → L5</small></div></button></div><div class="panel-foot">3 pessoas</div></section>`}
function managerPerson(body){return `<div class="split people">${directory()}<div class="stack">${personHeader()}${tabs([['people','Plano de carreira'],['managerevidence','Evidências'],['manageranalyses','Análises']],current)}${body}</div></div>`}
function viewContent(){let toolbar='',body='',cta='',subtitle='';
 switch(current){
 case 'overview':
 subtitle='Seu trabalho, organizado para a próxima conversa de carreira.';toolbar=dateTools();cta=link('inbox','Abrir caixa de entrada','link-button primary');
 body=`<div class="metrics"><div class="metric"><span class="sub">Análises salvas</span><strong>2</strong><small>Todo o período</small></div><div class="metric"><span class="sub">Critérios com apoio</span><strong>1 <span class="sub">/ 24</span></strong><small>Framework atual</small></div><div class="metric"><span class="sub">Fontes</span><strong>2</strong><small>GitHub e Slack</small></div></div><div class="callout"><div><strong>Reúna o contexto da sua próxima conversa</strong><small>Abra uma análise para conferir a leitura de impacto e a revisão.</small></div>${link('plan','Ver plano de carreira','link-button')}</div><div class="two fill">${panel('Análises recentes',`${listRow('Alinhamento sobre incidente','#platform · Slack · 10 mai. 2026')}${listRow('Autenticação OAuth e mentoria','PR #902 · GitHub · 3 mai. 2026')}`,link('analyses','Todas as análises →'))}${panel('Seu framework',`<div class="statusline">${badge('L4','purple')}<span>Software Engineer II</span></div><p>1 de 8 critérios deste nível possui evidência de apoio.</p><div class="bar"><span style="width:12.5%"></span></div><p class="note">Ausência de evidência não é uma avaliação negativa.</p>`,`${link('framework','Explorar critérios →')} ${link('reports','Ver relatórios →')}`)}</div>`;break;
 case 'inbox':case 'mobile':
 subtitle='Leia a fonte antes de analisar. Evidências dispensadas ficam em outra visualização.';cta=link('import','Importar PR','link-button primary');toolbar=`<label>Status <select id="inbox-status"><option>Pendentes · 4</option>Dispensadas · 3</option></select></label><label>Fonte <select><option>Todas</option><option>GitHub</option></select></label>${dateTools()}`;
 body=`<div class="split"><section class="panel"><div class="panel-head"><h2 id="inbox-list-title">4 pendentes</h2><span class="sub">Mais recentes</span></div><div class="row-list" id="inbox-rows">${[7,8,10,15].map((n,i)=>listRow(`PR #${n} · ${['Trusted analysis','Repeatable GitHub sync','Career insights','Sync stacked PRs'][i]}`,'PromovaGD/Promova · 21 ago. 2026','evidence','Pendente',i===0)).join('')}</div><div class="panel-foot">${pager(4)}</div></section><section class="panel preview-pane"><div class="panel-head"><div><h2>Trusted analysis</h2><small>PR #7 · GitHub</small></div>${badge('Pendente','purple')}</div><div class="panel-body">${sourceCopy()}<p class="note">Abra a evidência para incluir uma observação opcional antes de analisar.</p></div><div class="panel-foot">${action('Dispensar','confirm','danger','Dispensar PR #7? A fonte será preservada e o item sairá das pendências. Não há restauração disponível no fluxo atual.')}${link('evidence','Abrir evidência','link-button primary')}</div></section></div>`;break;
 case 'evidence':
 subtitle='João Silva / Caixa de entrada / GitHub';toolbar=`${link('inbox','← Caixa de entrada','link-button quiet')} ${badge('Pendente','purple')} <span class="sub">Fonte imutável</span>`;
 body=`<section class="panel fill"><div class="panel-head"><h2>Revise antes de analisar</h2></div><div class="panel-body"><div class="two"><div>${sourceCopy()}</div><div><label class="field">Sua observação <span class="sub">Opcional · separada da fonte</span><textarea id="observation" maxlength="2000" rows="8" placeholder="Acrescente contexto verificável.">${esc(observationDraft)}</textarea><small id="observation-count">${observationDraft.length}/2000</small></label><p class="note">A observação fica salva com esta análise. O texto original não é alterado.</p></div></div></div><div class="panel-foot"><span class="sub">Contexto atual: L3 → L4</span><div class="actions">${action('Dispensar','confirm','danger','Dispensar a evidência preserva a fonte. Este protótipo não altera dados.')}<button class="primary" data-analyze>Analisar evidência</button></div></div></section>`;break;
 case 'analyses':case 'manageranalyses':
 subtitle=current==='analyses'?'Resultados salvos, com o contexto de cada análise.':'Maria Santos / Histórico salvo';toolbar=`${dateTools()}<label>Fonte <select><option>Todas</option><option>GitHub</option><option>Slack</option></select></label>${current==='analyses'?link('reports','Relatórios','link-button') : ''}`;
 body=`<section class="panel fill"><div class="panel-head"><h2>2 análises salvas</h2>${current==='analyses'?action('Mais ações','confirm','','Limpar histórico? Na implementação, confirmar período, quantidade e remoção das análises e revisões. Evidências capturadas são recursos separados.'):badge('Leitura gerencial')}</div><div class="row-list">${listRow('Alinhamento sobre incidente','Slack · Confiança média · Impacto L4 · 10 mai. 2026',current==='analyses'?'analysis':'review')}${listRow('Autenticação OAuth e mentoria','GitHub · Alta confiança · Impacto L4 · 3 mai. 2026',current==='analyses'?'analysis':'review','Aceita')}</div><div class="panel-foot">${pager(2)}</div></section>`;if(current==='manageranalyses')body=managerPerson(body);break;
 case 'result':
 subtitle='João Silva / PR #7 / Resultado ilustrativo';toolbar=`${link('inbox','← Caixa de entrada','link-button quiet')}${badge('Análise salva','green')}${badge('Não revisada')}`;body=panel('Resultado da análise',`<div class="summary"><div><small>Impacto estimado · exemplo</small><div class="level">L4</div></div><div><strong>Contexto preservado: L3 → L4</strong><p class="sub">O resultado real será fornecido pelo servidor.</p></div></div><p>Fonte: PR #7 · Trusted server-owned analysis.</p><h3>Observação salva</h3><p>${esc(observationDraft||'Nenhuma observação registrada.')}</p><p class="note">Este estado demonstra o sucesso da operação sem alterar a fonte original.</p>`,`${link('inbox','Ver próxima pendência','link-button primary')}${link('analyses','Abrir análises →')}`,'fill');break;
 case 'analysis':case 'history':case 'source':
 subtitle='Maria Santos / Análise salva em 10 mai. 2026';toolbar=`${link('analyses','← Análises','link-button quiet')}${analysisTabs()}<span class="right">${badge('Precisa de contexto','amber')}</span>`;
 if(current==='analysis')body=panel('Leitura de impacto',analysisSummary(),`${link('history','Ver histórico de revisão →')}<span class="sub">Resultado imutável</span>`,'fill');
 if(current==='history')body=panel('Histórico de revisão',`<p class="note">Exemplo ilustrativo com eventos. O screenshot 06 mostra histórico vazio.</p><ol class="timeline"><li>${badge('Não revisada')}<small>10 mai. 2026, 15:45 · Análise salva</small><p>Aguardando uma revisão.</p></li><li>${badge('Precisa de contexto','amber')}<small>12 mai. 2026, 10:20 · Marina, gestora</small><p>Inclua na próxima conversa os resultados mensuráveis após a mitigação.</p></li></ol><p class="note">O histórico é somente leitura. Converse com seu gestor sobre o contexto solicitado.</p>`,`${link('source','Consultar fonte →')}<span class="sub">Cada revisão é um novo evento</span>`,'fill');
 if(current==='source')body=panel('Fonte salva com a análise',`<div class="statusline">${badge('Slack')}<span class="sub">#platform · Comunicação</span></div><p class="source">Conduziu alinhamento cross-team sobre incidente de produção e plano de mitigação.</p><h3>Observação no momento da análise</h3><p class="muted">Nenhuma observação registrada.</p><p class="note">Esta é a evidência preservada no resultado. Alterações futuras na integração não substituem este texto.</p>`,link('analysis','Voltar ao resumo →'),'fill');break;
 case 'reports':
 subtitle='Distribuições das análises salvas. Sem pontuação de promoção.';toolbar=`${link('analyses','← Análises','link-button quiet')}${dateTools()}<label>Visualização <select id="report-view"><option>Fontes</option><option>Níveis estimados</option><option>Tendência</option></select></label>`;
 body=panel('Distribuição no período',`<div id="report-content"><div class="report-row"><div><strong>GitHub</strong><span>1 análise · 50%</span></div><div class="bar"><span style="width:50%"></span></div></div><div class="report-row"><div><strong>Slack</strong><span>1 análise · 50%</span></div><div class="bar"><span style="width:50%"></span></div></div></div>`,'','fill');break;
 case 'managerframework':case 'framework':
 subtitle=current==='managerframework'?'Estrutura oficial · somente leitura. Autoria do framework fora deste escopo.':'Critérios do framework atual e evidências que os apoiam.';toolbar=`<label>Nível <select id="level-picker"><option>L4 · Software Engineer II</option><option>L3 · Software Engineer I</option><option>L5 · Sr. Software Engineer</option></select></label><label>Apoio <select id="support-picker"><option>Todos</option><option>Sem evidência</option><option>Com evidência</option></select></label>${dateTools()}`;
 body=`<div class="split"><section class="panel"><div class="panel-head"><h2>Critérios</h2><small id="criterion-count">8 critérios · 1 com apoio</small></div><div class="row-list" id="criterion-rows">${['Security','Writing code','Testing','Incident response & Debugging','Observability','Software Design & System Architecture','Cloud Infra','Work breakdown'].map((name,i)=>`<button class="row ${i===0?'selected':''}" style="width:100%;border-radius:0;justify-content:flex-start" data-criterion="${name}" data-supported="${i===0}"><div><strong>${name}</strong><small>${i===0?'1 análise de apoio':'Sem evidência no período'}</small></div></button>`).join('')}</div><div class="panel-foot"><span>Sem apoio não significa avaliação negativa.</span></div></section>${panel('Security',`<div id="criterion-detail"><div class="statusline">${badge('L4','purple')}${badge('Com evidência','green')}</div><h3>Definição</h3><p>Critério de segurança do framework oficial. A implementação exibirá a descrição integral fornecida pelo servidor.</p><h3>Evidência de apoio</h3>${listRow('PR #902 · auth-service','GitHub · 3 mai. 2026','analysis','L4')}<p class="note">Referências históricas sem identificador canônico permanecem legíveis, com “Detalhe indisponível”.</p></div>`,'','preview-pane')}</div>`;break;
 case 'criterion':
 subtitle='Framework / L4 / Security';toolbar=link('framework','← Critérios','link-button quiet');body=panel('Definição e evidências de apoio',`<p>Descrição oficial completa do critério, fornecida pelo framework.</p><h3>Evidências de apoio</h3>${listRow('PR #902 · auth-service','GitHub · 3 mai. 2026','analysis','L4')}<p class="note">Sem identificador canônico, a referência histórica permanece como texto.</p>`,'','fill');break;
 case 'managereadonly':
 subtitle='Pessoas / Maria Santos / Evidências';toolbar=`${link('managerevidence','← Evidências de Maria','link-button quiet')}${badge('Somente leitura')}${badge('Analisada','green')}`;body=panel('Fonte preservada',`<p class="source">Implementou autenticação OAuth e revisou PRs de colegas júnior.</p><h3>Origem</h3><p>GitHub · PR #902 · auth-service</p><p class="note">Visualização gerencial. A análise e a dispensa pertencem ao funcionário responsável pela fonte.</p>`,link('review','Abrir análise vinculada →'),'fill');break;
 case 'plan':case 'context':
 subtitle='Plano definido pela gestão · Maria Santos';toolbar=`${tabs([['plan','Objetivos'],['context','Contexto']],current)}${badge('Somente leitura')}`;
 body=current==='plan'?panel('Objetivos',objectiveBody(),`${selectField('Status',['Ativos','Concluídos','Arquivados'])}${link('framework','Ver framework →')}`,'fill'):panel('Seu contexto de carreira',`<div class="summary"><div><small>Cargo</small><h2>Engenharia de Software</h2></div><strong>L3 → L4</strong></div><h3>Características</h3><p class="muted">Nenhuma característica registrada.</p><h3>Níveis oficiais</h3>${listRow('L3 · Software Engineer I','Atual','framework','Atual')}${listRow('L4 · Software Engineer II','Alvo','framework','Alvo')}${listRow('L5 · Sr. Software Engineer','Disponível','framework','')}<p class="note">Alterações são feitas pelo gestor responsável.</p>`,link('plan','Ver objetivos →'),'fill');break;
 case 'integrations':case 'sync':case 'import':
 subtitle='GitHub / Integrações';toolbar=tabs([['integrations','Conexão'],['sync','Sincronização'],['import','Importar PR']],current);
 if(current==='integrations')body=panel('Configuração da conexão',`<div class="statusline">${badge('Configurado','purple')}<span class="sub">Acesso ainda não testado nesta sessão</span></div><div class="form-grid">${field('Repositório','PromovaGD/Promova')}${field('Login do autor','joaorihan')}</div><p class="note">O acesso usa a conexão disponibilizada pela empresa. Para repositórios sem acesso, peça ajuda ao responsável pela integração.</p><p class="sub">Salvar configuração não comprova acesso ao repositório.</p>`,`<div class="actions">${action('Desconectar','confirm','danger','Remover a configuração salva de repositório e autor? Evidências já capturadas permanecem disponíveis.')}${action('Testar acesso','notice','','Teste ilustrativo: acesso confirmado.')}</div>${action('Salvar configuração','notice','primary','Configuração salva — demonstração local.')}`,'fill');
 if(current==='sync')body=panel('Última sincronização',`<div class="statusline">${badge('Concluída','green')}<span class="sub">21 ago. 2026, 10:50 · Exemplo ilustrativo</span></div><p>PromovaGD/Promova · autor joaorihan</p><div class="metrics" style="margin-top:22px"><div class="metric"><small>Encontrados</small><strong>7</strong></div><div class="metric"><small>Novos</small><strong>4</strong></div><div class="metric"><small>Já existentes</small><strong>3</strong></div></div><p class="note">0 falhas. As evidências importadas aguardam sua revisão na Caixa de entrada.</p>`,`${link('inbox','Abrir 4 pendências →')}${action('Sincronizar PRs','notice','primary','Sincronização ilustrativa iniciada. Na implementação, atualizar resultado após resposta do servidor.')}`,'fill');
 if(current==='import')body=panel('Buscar ou importar um PR específico',`<p class="note">Usando a configuração salva: PromovaGD/Promova · joaorihan</p><div class="actions">${field('Número do PR','7','number','min="1"')}${action('Buscar PRs')}</div>${listRow('PR #7 · Trusted analysis','joaorihan · closed','evidence','Selecionado')}${listRow('PR #8 · Repeatable GitHub sync','joaorihan · closed','evidence','')}`,`<span class="sub">Importa a fonte antes da análise.</span>${link('evidence','Importar PR #7','link-button primary')}`,'fill');break;
 case 'people':
 subtitle='Encontre uma pessoa e abra seu contexto de carreira.';toolbar=`<label>Cargo <select><option>Todos</option><option>Engenharia</option></select></label><label>Nível <select><option>Todos</option><option>L3</option><option>L4</option></select></label><span class="sub desktop-only">Diretório e plano rolam independentemente</span>`;
 body=managerPerson(panel('Objetivos de carreira',objectiveBody(false),`<div class="actions">${link('managerplan','Editar contexto','link-button')}${action('Novo objetivo','objective','primary')}</div>`,'fill'));break;
 case 'managerplan':
 subtitle='Pessoas / Maria Santos / Plano de carreira';toolbar=`${link('people','← Plano de Maria','link-button quiet')}${badge('Edição gerencial','purple')}`;
 body=panel('Contexto de carreira',`<div class="reading">${selectField('Cargo',['Engenharia de Software','Staff Software Engineer'])}<div class="form-grid">${selectField('Nível atual',['L3 · Software Engineer I','L4 · Software Engineer II'])}${selectField('Nível alvo',['L4 · Software Engineer II','L5 · Sr. Software Engineer'])}</div><label class="field">Características<textarea placeholder="Separe por vírgulas ou linhas"></textarea><small>Os níveis disponíveis respeitam o cargo selecionado.</small></label><p class="note">Objetivos são gerenciados em sua própria visualização. Esta alteração vale para o plano atual e novas análises.</p></div>`,`${link('people','Cancelar','link-button')}${action('Salvar plano','notice','primary','Plano salvo — demonstração local. Atualizar resumo da pessoa após confirmação do servidor.')}`,'fill');break;
 case 'managerevidence':
 subtitle='Pessoas / Maria Santos';toolbar=`<label>Status <select><option>Todos</option><option>Pendentes</option><option>Analisadas</option><option>Dispensadas</option></select></label>${dateTools()}`;
 body=managerPerson(`<section class="panel fill"><div class="panel-head"><h2>Evidências capturadas</h2>${badge('Somente leitura')}</div><div class="row-list">${listRow('PR #902 · auth-service','GitHub · 3 mai. 2026','managereadonly','Analisada')}${listRow('#platform · Comunicação','Slack · 10 mai. 2026','managereadonly','Analisada')}</div><div class="panel-foot">${pager(2)}</div></section>`);break;
 case 'reviews':
 subtitle='Análises aguardando sua leitura e decisão.';toolbar=`<label>Status <select id="review-status"><option>Não revisadas</option><option>Precisam de contexto</option><option>Aceitas</option></select></label><label>Pessoa <select><option>Todas</option><option>Maria Santos</option></select></label>${dateTools()}`;
 body=`<section class="panel fill"><div class="panel-head"><h2>Fila de revisão</h2><span class="sub">Mais antigas primeiro · conceito</span></div><div class="row-list">${listRow('Comunicação · #platform','Maria Santos · Slack · 10 mai. 2026','review')}${listRow('Autenticação OAuth e mentoria','Maria Santos · GitHub · 3 mai. 2026','review')}</div><div class="panel-foot">${pager(2)}</div></section>`;break;
 case 'review':
 subtitle='Pessoas / Maria Santos / Análises / Comunicação';toolbar=`${link('reviews','← Fila de revisão','link-button quiet')} ${badge('Não revisada')} <span class="sub">Análise salva em 10 mai. 2026</span><button class="mobile-only" id="review-facet" aria-pressed="false">Consultar resultado</button>`;
 body=`<div class="split review-layout"><section class="panel review-summary"><div class="panel-head"><h2>Resultado da análise</h2></div><div class="panel-body">${analysisSummary()}<details><summary>Fonte salva</summary><p class="source">Conduziu alinhamento cross-team sobre incidente de produção e plano de mitigação.</p></details></div></section><section class="panel review-editor"><div class="panel-head"><h2>Registrar revisão</h2>${badge('Gestor','purple')}</div><div class="panel-body"><p>Registre uma decisão sobre esta análise. Cada ação acrescenta um evento ao histórico.</p><label class="field" style="margin-top:22px">Comentário opcional<textarea id="review-comment" maxlength="2000" rows="6" placeholder="Contexto que acompanha a decisão">${esc(reviewerDraft)}</textarea><small id="review-count">${reviewerDraft.length}/2000</small></label><details open><summary>Histórico atual</summary><p class="note" id="review-history">Nenhum evento registrado. Análise não revisada.</p></details></div><div class="panel-foot"><button data-review="NEEDS_CONTEXT">Pedir mais contexto</button><button class="primary" data-review="ACCEPTED">Aceitar análise</button></div></section></div>`;break;
 case 'roles':
 subtitle='Cargos, terminologia e estrutura oficial da organização.';toolbar=configTabs();cta=action('Novo cargo','role','primary');
 body=`<section class="panel fill"><div class="panel-head"><h2>Cargos</h2><label class="sub">Status <select><option>Ativos</option><option>Arquivados</option></select></label></div><div class="row-list">${listRow('Engenharia de Software','L3, L4, L5 · Desenvolvimento e evolução de produtos','role','Ativo')}${listRow('Staff Software Engineer','L4, L5','role','Ativo')}</div><div class="panel-foot">${pager(2)}</div></section>`;break;
 case 'role':
 subtitle='Configuração de carreira / Cargos';toolbar=link('roles','← Cargos','link-button quiet');
 body=panel('Editar cargo',`<div class="reading">${field('Nome','Engenharia de Software')}<label class="field">Descrição<textarea>Desenvolvimento e evolução de produtos de software.</textarea></label><fieldset class="checks"><legend>Níveis permitidos</legend>${['L3 · Software Engineer I','L4 · Software Engineer II','L5 · Sr. Software Engineer'].map(v=>`<label><input type="checkbox" checked>${v}</label>`).join('')}</fieldset><p class="note">Selecione pelo menos um nível. A ordem e os critérios vêm do framework oficial.</p></div>`,`<div class="actions">${link('roles','Cancelar','link-button')}${action('Arquivar cargo','archive','danger')}</div>${action('Salvar alterações','notice','primary','Cargo atualizado — demonstração local.')}`,'fill');break;
 case 'terminology':
 subtitle='Rótulos usados nas superfícies de gestão e carreira.';toolbar=configTabs();
 body=panel('Rótulos da organização',`<div class="form-grid reading">${['Gestor','Funcionário','Cargo','Nível','Características','Objetivo'].map(x=>field(x,x)).join('')}</div><p class="note">Prévia: “Plano de carreira do Funcionário” · As permissões e os endereços permanecem estáveis.</p>`,action('Salvar terminologia','notice','primary','Terminologia atualizada — demonstração local.'),'fill');break;
 case 'loading':case 'empty':case 'error':
 toolbar=`${dateTools()}<label>Status <select><option>Pendentes</option></select></label>`;cta=link('import','Importar PR','link-button');
 if(current==='loading')body=`<section class="panel fill" aria-busy="true"><div class="panel-head"><h2>Carregando evidências…</h2></div><div class="row-list">${Array.from({length:4},()=>'<div class="placeholder-row"><div class="skeleton short"></div><div class="skeleton"></div></div>').join('')}</div><div class="panel-foot"><span>Seu espaço permanece no lugar.</span></div></section>`;
 if(current==='empty')body=`<section class="panel fill"><div class="empty"><span class="state-symbol" aria-hidden="true">✓</span><h2>Sua caixa de entrada está em dia</h2><p>Nenhuma evidência pendente. Você pode importar um PR ou consultar suas análises salvas.</p><div class="actions">${link('import','Importar PR','link-button primary')}${link('analyses','Ver análises','link-button')}</div></div></section>`;
 if(current==='error')body=`<section class="panel fill"><div class="empty" role="alert"><span class="state-symbol" aria-hidden="true">!</span><h2>Não foi possível carregar as evidências</h2><p>Seus filtros foram mantidos. Tente novamente para atualizar esta lista.</p><div class="actions">${link('inbox','Tentar novamente','link-button primary')}${link('overview','Ir à visão geral','link-button')}</div><small>A sessão permanece ativa.</small></div></section>`;break;
 case 'denied':toolbar='';body=`<section class="panel fill"><div class="empty"><span class="state-symbol" aria-hidden="true">⊘</span><h2>Você não pode acessar este recurso</h2><p>Sua conta continua conectada. Abra uma área disponível para seu perfil.</p>${link('overview','Ir à visão geral','link-button primary')}</div></section>`;break;
 }
 if(current==='managerframework'){toolbar=configTabs();body=panel('Níveis e critérios oficiais',`<label class="field">Nível<select><option>L4 · Software Engineer II</option><option>L3 · Software Engineer I</option><option>L5 · Sr. Software Engineer</option></select></label><div class="note">A configuração atual permite selecionar níveis por cargo. Não oferece edição dos critérios do framework.</div>${['Writing code','Testing','Security','Software Design & System Architecture'].map(x=>`<details class="row" style="display:block"><summary>${x}</summary><p class="sub">Descrição integral do framework oficial. Conteúdo de exemplo para o wireframe.</p></details>`).join('')}`,'Somente leitura','fill');}
 return {toolbar,body,cta,subtitle};
}
function publicPage(){return `<div class="public"><header>${brand('public')}<nav class="tabs"><a href="#product" data-public-anchor="product">Produto</a><a href="#how" data-public-anchor="how">Como funciona</a></nav><div class="actions">${link('login','Entrar','link-button')}${link('register','Começar','link-button primary')}</div></header><section id="product" class="hero"><div><div class="eyebrow">Carreira com contexto</div><h1>Evidências claras. Conversas melhores.</h1><p>Organize seu trabalho, entenda os critérios de carreira e prepare sua próxima conversa com a gestão.</p>${link('register','Começar agora','link-button primary')}</div>${panel('Do trabalho à conversa',`${listRow('1 · Capture uma evidência','Importe um PR do GitHub','login','')}${listRow('2 · Confira a leitura de impacto','Preserve a fonte e acrescente contexto','login','')}${listRow('3 · Converse sobre sua evolução','Com critérios claros e histórico de revisão','login','')}`)}</section><section id="how"><h2>Um fluxo simples, com evidências preservadas</h2><div class="two">${panel('Para quem desenvolve','Encontre suas pendências, análises e plano em espaços próprios.')}${panel('Para quem lidera','Consulte pessoas e registre revisões com histórico visível.')}</div></section><section style="background:#f4f0ff"><h2>Conectado ao seu trabalho</h2><p>Importação de pull requests do GitHub disponível. Outros provedores não são apresentados como conexões ativas.</p></section><footer>Promova · Evolução de carreira com evidências</footer></div>`}
function authPage(){const register=current==='register';return `<div class="auth-wrap">${brand('public')}<section class="panel"><div class="auth-card"><h1>${register?'Criar sua conta':'Entrar na sua conta'}</h1><p class="sub">${register?'Comece a organizar suas evidências.':'Acesse seu espaço de carreira.'}</p>${register?field('Nome completo','','text','autocomplete="name"'):''}${field('E-mail','','email','autocomplete="email"')}${field('Senha','','password',`autocomplete="${register?'new-password':'current-password'}" minlength="6"`)}${action(register?'Criar conta':'Entrar','notice','primary','Fluxo de autenticação ilustrativo. Nenhuma credencial é enviada.')}<p class="sub">${register?'Já tem conta? '+link('login','Entrar'):'Ainda não tem conta? '+link('register','Cadastre-se')}</p></div></section></div>`}
function render(){const hash=location.hash.slice(1);current=scenes[hash]?hash:'overview';selector.value=current;const [label,title,path,role,selected]=scenes[current];document.title=`${label} · Promova wireframes`;
 if(role==='public'){root.innerHTML=current==='landing'?publicPage():authPage();return}
 const {toolbar,body,cta,subtitle}=viewContent();
 root.innerHTML=`<div class="app"><a class="skip" href="#main-title" data-focus-main>Pular para conteúdo</a><aside class="sidebar">${brand(role)}<div>${nav(role,selected)}</div><div class="side-bottom"><small>Promova · ${role==='manager'?'Gestão':'Carreira'}</small>${link('landing','Site público','link-button quiet')}</div></aside><div class="main-shell"><header class="topbar"><button class="menu-button" id="menu-trigger" aria-label="Abrir menu" aria-haspopup="dialog" aria-expanded="false">☰ Menu</button><span class="top-context">${role==='manager'?'Espaço de gestão':'Meu espaço de carreira'}</span><button class="account quiet" data-account><span class="avatar">${role==='manager'?'MG':current==='inbox'||current==='mobile'||current==='evidence'||current==='result'?'JS':'MS'}</span><span class="account-name">${role==='manager'?'Marina · Gestora':current==='inbox'||current==='mobile'||current==='evidence'||current==='result'?'João Silva':'Maria Santos'}</span><span aria-hidden="true">⌄</span></button></header><div class="page-head"><div><div id="route-note">${esc(path)}</div><h1 id="main-title" tabindex="-1">${title}</h1>${subtitle?`<span class="sub">${subtitle}</span>`:''}</div><div class="actions">${cta}</div></div><div class="toolbar">${toolbar}</div><main class="content" aria-labelledby="main-title">${body}</main></div></div>`;
 document.getElementById('drawer-links').innerHTML=nav(role,selected)+`<div class="side-bottom">${link('landing','Site público','link-button quiet')}${link('login','Sair','link-button quiet')}</div>`;
 if(current==='mobile')openNavigation();
}
function openNavigation(){document.getElementById('menu-trigger')?.setAttribute('aria-expanded','true');document.getElementById('navigation').showModal()}
function showNotice(message){const n=document.getElementById('notice');n.textContent=message;n.classList.add('shown');clearTimeout(showNotice.timer);showNotice.timer=setTimeout(()=>n.classList.remove('shown'),5000)}
function dialog(title,body){document.getElementById('dialog-title').textContent=title;document.getElementById('dialog-body').innerHTML=body;document.getElementById('action-dialog').showModal()}
selector.innerHTML=Object.entries(scenes).map(([id,[label]])=>`<option value="${id}">${label}</option>`).join('');
selector.addEventListener('change',()=>location.hash=selector.value);
window.addEventListener('hashchange',()=>{document.getElementById('navigation').close();document.getElementById('action-dialog').close();render();document.getElementById('main-title')?.focus({preventScroll:true})});
document.addEventListener('click',event=>{
 const a=event.target.closest('a');if(a?.dataset.publicAnchor){event.preventDefault();document.getElementById(a.dataset.publicAnchor)?.scrollIntoView({behavior:'smooth'});return}
 if(event.target.closest('[data-focus-main]')){event.preventDefault();document.getElementById('main-title')?.focus();return}
 const b=event.target.closest('button');if(!b)return;
 if(b.id==='menu-trigger')openNavigation();
 if(b.id==='review-facet'){const split=document.querySelector('.review-layout');const selected=split.classList.toggle('show-summary');b.setAttribute('aria-pressed',String(selected));b.textContent=selected?'Voltar à decisão':'Consultar resultado';}
 if(b.hasAttribute('data-close'))document.getElementById('navigation').close();
 if(b.dataset.notice)showNotice(b.dataset.notice);
 if(b.dataset.confirm)dialog('Confirmar ação',`<p>${esc(b.dataset.confirm)}</p><p class="note">Demonstração de confirmação. Nenhum dado do produto será alterado.</p>`);
 if(b.hasAttribute('data-account'))dialog('Sua conta',`<p>Perfil: ${scenes[current][3]==='manager'?'Gestor':'Funcionário'}</p><p class="note">Identidade e permissões vêm da sessão validada.</p>${link('login','Sair da demonstração','link-button')}`);
 if(b.hasAttribute('data-objective'))dialog('Novo objetivo',`${field('Objetivo')}${selectField('Status',['Ativo','Concluído','Arquivado'])}${field('Data alvo','','date')}<p class="sub">Editor ilustrativo. No produto, será uma rota própria com apresentação em painel no desktop.</p>`);
 if(b.hasAttribute('data-role'))dialog('Novo cargo',`${field('Nome')}${field('Descrição')}${selectField('Níveis permitidos',['L3, L4, L5','L4, L5'])}`);
 if(b.hasAttribute('data-archive'))dialog('Arquivar cargo',`<p>Usuários atribuídos precisam de um cargo alternativo compatível.</p>${selectField('Cargo alternativo',['Selecione uma alternativa','Staff Software Engineer'])}<p class="note">A implementação deve carregar quantidade de atribuições e validar a compatibilidade antes de confirmar.</p>`);
 if(b.hasAttribute('data-analyze')){b.disabled=true;b.textContent='Analisando…';showNotice('Simulação local; a análise real deve ser confirmada pelo servidor.');setTimeout(()=>{location.hash='result';showNotice('Análise salva — resultado ilustrativo.');},700)}
 if(b.dataset.review){reviewerDraft=document.getElementById('review-comment').value;document.getElementById('review-history').textContent=`${b.dataset.review==='ACCEPTED'?'Aceita':'Precisa de contexto'} · Marina · Agora${reviewerDraft?' — '+reviewerDraft:''} (evento ilustrativo)`;showNotice('Revisão registrada na demonstração. Nenhum dado foi enviado.');}
 if(b.dataset.criterion){document.querySelectorAll('[data-criterion]').forEach(x=>x.classList.toggle('selected',x===b));const text=`<div class="statusline">${badge('L4','purple')}${badge(b.dataset.supported==='true'?'Com evidência':'Sem evidência')}</div><h3>${esc(b.dataset.criterion)}</h3><p>Descrição oficial do critério fornecida pelo framework. A implementação mantém o texto integral e referências de apoio em uma rota dedicada.</p>`;document.getElementById('criterion-detail').innerHTML=text;if(innerWidth<900)location.hash='criterion';}
});
document.getElementById('navigation').addEventListener('close',()=>{document.getElementById('menu-trigger')?.setAttribute('aria-expanded','false')});
document.getElementById('action-dialog').addEventListener('close',()=>{if(document.getElementById('action-dialog').returnValue==='confirm')showNotice('Confirmação ilustrativa. Nenhum dado do produto foi alterado.')});
document.addEventListener('input',event=>{const el=event.target;if(el.id==='review-comment'){reviewerDraft=el.value;document.getElementById('review-count').textContent=el.value.length+'/2000'}if(el.id==='observation'){observationDraft=el.value;document.getElementById('observation-count').textContent=el.value.length+'/2000'}if(el.id==='people-search')document.querySelectorAll('#people-list .row').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(el.value.toLowerCase()))});
document.addEventListener('change',event=>{
 if(event.target.id==='support-picker'){const chosen=event.target.selectedIndex;document.querySelectorAll('[data-criterion]').forEach(row=>row.hidden=chosen===1?row.dataset.supported==='true':chosen===2?row.dataset.supported!=='true':false);document.getElementById('criterion-count').textContent=chosen===1?'7 critérios sem apoio':chosen===2?'1 critério com apoio':'8 critérios · 1 com apoio';}
 if(event.target.id==='inbox-status'){const dismissed=event.target.selectedIndex===1;document.getElementById('inbox-list-title').textContent=dismissed?'3 dispensadas':'4 pendentes';document.getElementById('inbox-rows').innerHTML=(dismissed?[18,11,13]:[7,8,10,15]).map(n=>listRow(`PR #${n} · PromovaGD/Promova`,'GitHub · Registro capturado',dismissed?'empty':'evidence',dismissed?'Dispensada':'Pendente')).join('');showNotice('Filtro ilustrativo aplicado. No produto, o status e a página ficam na URL.');}
 if(event.target.id==='report-view'){const v=event.target.selectedIndex;document.getElementById('report-content').innerHTML=v===1?'<div class="report-row"><div><strong>L4</strong><span>2 análises · 100%</span></div><div class="bar"><span style="width:100%"></span></div></div>':v===2?'<div class="report-row"><div><strong>03–04 maio</strong><span>1 análise</span></div><div class="bar"><span style="width:50%"></span></div></div><div class="report-row"><div><strong>09–10 maio</strong><span>1 análise</span></div><div class="bar"><span style="width:50%"></span></div></div>':'<div class="report-row"><div><strong>GitHub</strong><span>1 · 50%</span></div><div class="bar"><span style="width:50%"></span></div></div><div class="report-row"><div><strong>Slack</strong><span>1 · 50%</span></div><div class="bar"><span style="width:50%"></span></div></div>';}
});
render();
