-- Promova schema ownership starts here. Keep later changes in a new versioned migration.
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('EMPLOYEE', 'ADMIN'))
);

CREATE TABLE auth_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_auth_sessions_token UNIQUE (token),
    CONSTRAINT fk_auth_sessions_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE career_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    current_level VARCHAR(255) NOT NULL,
    target_level VARCHAR(255) NOT NULL,
    CONSTRAINT uk_career_profiles_user UNIQUE (user_id),
    CONSTRAINT fk_career_profiles_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE evidences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    source VARCHAR(100) NOT NULL,
    external_id VARCHAR(500) NOT NULL,
    source_meta VARCHAR(1000) NOT NULL,
    evidence VARCHAR(10000) NOT NULL,
    source_url VARCHAR(2048),
    captured_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    status VARCHAR(30) NOT NULL,
    CONSTRAINT uk_evidences_user_source_external UNIQUE (user_id, source, external_id),
    CONSTRAINT fk_evidences_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ck_evidences_status CHECK (status IN ('PENDING', 'ANALYZED', 'DISMISSED'))
);

CREATE TABLE github_connection_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    repo_slug VARCHAR(255),
    author_login VARCHAR(39),
    last_sync_at TIMESTAMP(6) WITH TIME ZONE,
    last_sync_outcome VARCHAR(100) NOT NULL,
    CONSTRAINT uk_github_settings_user UNIQUE (user_id),
    CONSTRAINT fk_github_settings_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE saved_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_id VARCHAR(500) NOT NULL,
    user_id BIGINT NOT NULL,
    evidence_id BIGINT,
    source VARCHAR(100) NOT NULL,
    source_meta VARCHAR(1000) NOT NULL,
    evidence VARCHAR(10000) NOT NULL,
    current_level VARCHAR(255) NOT NULL,
    target_level VARCHAR(255) NOT NULL,
    impact_level VARCHAR(255) NOT NULL,
    confidence VARCHAR(255) NOT NULL,
    justification VARCHAR(4000) NOT NULL,
    competencies_json VARCHAR(4000) NOT NULL,
    suggestions_json VARCHAR(4000) NOT NULL,
    readiness VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_saved_analyses_evidence UNIQUE (evidence_id),
    CONSTRAINT fk_saved_analyses_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_saved_analyses_evidence FOREIGN KEY (evidence_id) REFERENCES evidences (id)
);

CREATE INDEX ix_auth_sessions_user_id ON auth_sessions (user_id);
CREATE INDEX ix_evidences_user_status_captured_at
    ON evidences (user_id, status, captured_at, id);
CREATE INDEX ix_saved_analyses_user_created_at
    ON saved_analyses (user_id, created_at, id);
