CREATE TABLE saved_analysis_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    saved_analysis_id BIGINT NOT NULL,
    reviewer_user_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    comment VARCHAR(2000),
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_saved_analysis_reviews_analysis
        FOREIGN KEY (saved_analysis_id) REFERENCES saved_analyses (id),
    CONSTRAINT fk_saved_analysis_reviews_reviewer
        FOREIGN KEY (reviewer_user_id) REFERENCES users (id),
    CONSTRAINT ck_saved_analysis_reviews_status
        CHECK (status IN ('UNREVIEWED', 'ACCEPTED', 'NEEDS_CONTEXT'))
);

CREATE INDEX ix_saved_analysis_reviews_history
    ON saved_analysis_reviews (saved_analysis_id, created_at, id);
