CREATE TABLE terminology_settings (
    id BIGINT PRIMARY KEY,
    manager_label VARCHAR(80) NOT NULL,
    employee_label VARCHAR(80) NOT NULL,
    job_role_label VARCHAR(80) NOT NULL,
    level_label VARCHAR(80) NOT NULL,
    characteristics_label VARCHAR(80) NOT NULL,
    objective_label VARCHAR(80) NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

INSERT INTO terminology_settings (
    id, manager_label, employee_label, job_role_label, level_label,
    characteristics_label, objective_label, updated_at
) VALUES (
    1, 'Gestor', 'Funcionário', 'Cargo', 'Nível', 'Características', 'Objetivo', CURRENT_TIMESTAMP
);

CREATE TABLE job_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_job_roles_name UNIQUE (name),
    CONSTRAINT ck_job_roles_status CHECK (status IN ('ACTIVE', 'ARCHIVED'))
);

CREATE TABLE job_role_levels (
    job_role_id BIGINT NOT NULL,
    sort_order INTEGER NOT NULL,
    level_id VARCHAR(40) NOT NULL,
    PRIMARY KEY (job_role_id, sort_order),
    CONSTRAINT uk_job_role_levels_level UNIQUE (job_role_id, level_id),
    CONSTRAINT fk_job_role_levels_role FOREIGN KEY (job_role_id) REFERENCES job_roles (id)
);

INSERT INTO job_roles (name, description, status, created_at, updated_at)
VALUES ('Engenharia de Software', 'Desenvolvimento e evolução de produtos de software.', 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO job_role_levels (job_role_id, sort_order, level_id)
SELECT id, 0, 'L3' FROM job_roles WHERE name = 'Engenharia de Software';
INSERT INTO job_role_levels (job_role_id, sort_order, level_id)
SELECT id, 1, 'L4' FROM job_roles WHERE name = 'Engenharia de Software';
INSERT INTO job_role_levels (job_role_id, sort_order, level_id)
SELECT id, 2, 'L5' FROM job_roles WHERE name = 'Engenharia de Software';

ALTER TABLE career_profiles ADD COLUMN job_role_id BIGINT;
ALTER TABLE career_profiles
    ADD CONSTRAINT fk_career_profiles_job_role FOREIGN KEY (job_role_id) REFERENCES job_roles (id);
CREATE INDEX ix_career_profiles_job_role ON career_profiles (job_role_id);
