ALTER TABLE career_profiles ADD COLUMN created_at TIMESTAMP(6) WITH TIME ZONE;
ALTER TABLE career_profiles ADD COLUMN updated_at TIMESTAMP(6) WITH TIME ZONE;
UPDATE career_profiles SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;
UPDATE career_profiles SET updated_at = CURRENT_TIMESTAMP WHERE updated_at IS NULL;

UPDATE career_profiles
SET job_role_id = (SELECT MIN(id) FROM job_roles WHERE status = 'ACTIVE')
WHERE job_role_id IS NULL;

ALTER TABLE career_profiles ALTER COLUMN job_role_id SET NOT NULL;
ALTER TABLE career_profiles ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE career_profiles ALTER COLUMN updated_at SET NOT NULL;

CREATE TABLE career_profile_characteristics (
    career_profile_id BIGINT NOT NULL,
    sort_order INTEGER NOT NULL,
    characteristic VARCHAR(120) NOT NULL,
    PRIMARY KEY (career_profile_id, sort_order),
    CONSTRAINT fk_profile_characteristics_profile
        FOREIGN KEY (career_profile_id) REFERENCES career_profiles (id)
);

CREATE TABLE career_objectives (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    career_profile_id BIGINT NOT NULL,
    text VARCHAR(1000) NOT NULL,
    status VARCHAR(20) NOT NULL,
    target_date DATE,
    created_by BIGINT NOT NULL,
    updated_by BIGINT NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_career_objectives_status CHECK (status IN ('ACTIVE', 'COMPLETED', 'ARCHIVED')),
    CONSTRAINT fk_career_objectives_profile FOREIGN KEY (career_profile_id) REFERENCES career_profiles (id),
    CONSTRAINT fk_career_objectives_created_by FOREIGN KEY (created_by) REFERENCES users (id),
    CONSTRAINT fk_career_objectives_updated_by FOREIGN KEY (updated_by) REFERENCES users (id)
);

CREATE INDEX ix_career_objectives_profile_status
    ON career_objectives (career_profile_id, status, id);
